name: lint

on:
  push:
    branches: main
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  superlinter:
    timeout-minutes: 5
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: super-linter/super-linter/slim@v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ./
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true
          GITHUB_ACTIONS_COMMAND_ARGS: -ignore 'label "windows-2025" is unknown'
          VALIDATE_GITLEAKS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_NATURAL_LANGUAGE: true

  codeql:
    timeout-minutes: 5
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.7'
      - run: pip3 install meson
      - run: pip3 install ninja

      # init
      - uses: github/codeql-action/init@v3
        with:
          languages: c-cpp

      # build
      - run: CXX=g++-14 meson setup build
      - run: meson compile -C build

      # analyze
      - uses: github/codeql-action/analyze@v3

  clang-tidy:
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 5
    runs-on: macos-15

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.7'
      - run: pip3 install meson
      - run: pip3 install ninja

      # build
      - run: CXX=$(brew --prefix llvm@18)/bin/clang++ meson setup build -Dbuildtype=${{ matrix.buildtypes }}
      - run: meson compile -C build

      # clang-tidy
      - run: gh pr diff --name-only | $(brew --prefix llvm@18)/bin/clang-tidy -path build --config-file=.clang-tidy --export-fixes=clang-tidy-result-fixes.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: platisd/clang-tidy-pr-comments@
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: clang-tidy-result-fixes.yml

