name: review

on:
  pull_request:
    branches: main
    paths:
      - '**.h'
      - '**.hpp'
      - '**.cc'
      - '**.cpp'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clang-tidy:
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 5
    runs-on: macos-15

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.7'
      - run: pip3 install meson
      - run: pip3 install ninja

      # build
      - run: CXX=$(brew --prefix llvm@18)/bin/clang++ meson setup build
      - run: meson compile -C build

      # clang-tidy
      - run: gh pr diff ${{ github.ref_name }} --name-only | "$(brew --prefix llvm@18)"/bin/run-clang-tidy -p build -config-file=.clang-tidy -export-fixes=clang-tidy-result-fixes.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: ${PATH}:$(brew --prefix llvm@18)/bin/clang-tidy

      - uses: platisd/clang-tidy-pr-comments@a8811fa17cd6bd02c52a3791b44f9840777e396a # v1.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: clang-tidy-result-fixes.yml

